// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: mantis/matching.proto

package mantis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          Side                   `protobuf:"varint,2,opt,name=side,proto3,enum=mantis.Side" json:"side,omitempty"`
	OrderType     OrderType              `protobuf:"varint,3,opt,name=order_type,json=orderType,proto3,enum=mantis.OrderType" json:"order_type,omitempty"`
	TimeInForce   TimeInForce            `protobuf:"varint,4,opt,name=time_in_force,json=timeInForce,proto3,enum=mantis.TimeInForce" json:"time_in_force,omitempty"`
	Price         string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderRequest) Reset() {
	*x = SubmitOrderRequest{}
	mi := &file_mantis_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderRequest) ProtoMessage() {}

func (x *SubmitOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderRequest.ProtoReflect.Descriptor instead.
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return file_mantis_matching_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubmitOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *SubmitOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *SubmitOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type SubmitOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitOrderResponse) Reset() {
	*x = SubmitOrderResponse{}
	mi := &file_mantis_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitOrderResponse) ProtoMessage() {}

func (x *SubmitOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitOrderResponse.ProtoReflect.Descriptor instead.
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return file_mantis_matching_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *SubmitOrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_mantis_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_mantis_matching_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"` // The cancelled order, if found.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_mantis_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_mantis_matching_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetDepthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MaxLevels     int32                  `protobuf:"varint,2,opt,name=max_levels,json=maxLevels,proto3" json:"max_levels,omitempty"` // Max price levels per side. Default 20.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthRequest) Reset() {
	*x = GetDepthRequest{}
	mi := &file_mantis_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthRequest) ProtoMessage() {}

func (x *GetDepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthRequest.ProtoReflect.Descriptor instead.
func (*GetDepthRequest) Descriptor() ([]byte, []int) {
	return file_mantis_matching_proto_rawDescGZIP(), []int{4}
}

func (x *GetDepthRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetDepthRequest) GetMaxLevels() int32 {
	if x != nil {
		return x.MaxLevels
	}
	return 0
}

type GetDepthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depth         *OrderBookDepth        `protobuf:"bytes,1,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepthResponse) Reset() {
	*x = GetDepthResponse{}
	mi := &file_mantis_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepthResponse) ProtoMessage() {}

func (x *GetDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepthResponse.ProtoReflect.Descriptor instead.
func (*GetDepthResponse) Descriptor() ([]byte, []int) {
	return file_mantis_matching_proto_rawDescGZIP(), []int{5}
}

func (x *GetDepthResponse) GetDepth() *OrderBookDepth {
	if x != nil {
		return x.Depth
	}
	return nil
}

type StreamTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Empty = all symbols.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTradesRequest) Reset() {
	*x = StreamTradesRequest{}
	mi := &file_mantis_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTradesRequest) ProtoMessage() {}

func (x *StreamTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTradesRequest.ProtoReflect.Descriptor instead.
func (*StreamTradesRequest) Descriptor() ([]byte, []int) {
	return file_mantis_matching_proto_rawDescGZIP(), []int{6}
}

func (x *StreamTradesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type TradeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trade         *Trade                 `protobuf:"bytes,1,opt,name=trade,proto3" json:"trade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeEvent) Reset() {
	*x = TradeEvent{}
	mi := &file_mantis_matching_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeEvent) ProtoMessage() {}

func (x *TradeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_matching_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeEvent.ProtoReflect.Descriptor instead.
func (*TradeEvent) Descriptor() ([]byte, []int) {
	return file_mantis_matching_proto_rawDescGZIP(), []int{7}
}

func (x *TradeEvent) GetTrade() *Trade {
	if x != nil {
		return x.Trade
	}
	return nil
}

var File_mantis_matching_proto protoreflect.FileDescriptor

const file_mantis_matching_proto_rawDesc = "" +
	"\n" +
	"\x15mantis/matching.proto\x12\x06mantis\x1a\x12mantis/types.proto\"\xeb\x01\n" +
	"\x12SubmitOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12 \n" +
	"\x04side\x18\x02 \x01(\x0e2\f.mantis.SideR\x04side\x120\n" +
	"\n" +
	"order_type\x18\x03 \x01(\x0e2\x11.mantis.OrderTypeR\torderType\x127\n" +
	"\rtime_in_force\x18\x04 \x01(\x0e2\x13.mantis.TimeInForceR\vtimeInForce\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\"a\n" +
	"\x13SubmitOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.mantis.OrderR\x05order\x12%\n" +
	"\x06trades\x18\x02 \x03(\v2\r.mantis.TradeR\x06trades\"G\n" +
	"\x12CancelOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"T\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\x05order\x18\x02 \x01(\v2\r.mantis.OrderR\x05order\"H\n" +
	"\x0fGetDepthRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"max_levels\x18\x02 \x01(\x05R\tmaxLevels\"@\n" +
	"\x10GetDepthResponse\x12,\n" +
	"\x05depth\x18\x01 \x01(\v2\x16.mantis.OrderBookDepthR\x05depth\"-\n" +
	"\x13StreamTradesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"1\n" +
	"\n" +
	"TradeEvent\x12#\n" +
	"\x05trade\x18\x01 \x01(\v2\r.mantis.TradeR\x05trade2\xa2\x02\n" +
	"\x0eMatchingEngine\x12F\n" +
	"\vSubmitOrder\x12\x1a.mantis.SubmitOrderRequest\x1a\x1b.mantis.SubmitOrderResponse\x12F\n" +
	"\vCancelOrder\x12\x1a.mantis.CancelOrderRequest\x1a\x1b.mantis.CancelOrderResponse\x12=\n" +
	"\bGetDepth\x12\x17.mantis.GetDepthRequest\x1a\x18.mantis.GetDepthResponse\x12A\n" +
	"\fStreamTrades\x12\x1b.mantis.StreamTradesRequest\x1a\x12.mantis.TradeEvent0\x01B8Z6github.com/mantis-exchange/mantis-common/gen/go/mantisb\x06proto3"

var (
	file_mantis_matching_proto_rawDescOnce sync.Once
	file_mantis_matching_proto_rawDescData []byte
)

func file_mantis_matching_proto_rawDescGZIP() []byte {
	file_mantis_matching_proto_rawDescOnce.Do(func() {
		file_mantis_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mantis_matching_proto_rawDesc), len(file_mantis_matching_proto_rawDesc)))
	})
	return file_mantis_matching_proto_rawDescData
}

var file_mantis_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mantis_matching_proto_goTypes = []any{
	(*SubmitOrderRequest)(nil),  // 0: mantis.SubmitOrderRequest
	(*SubmitOrderResponse)(nil), // 1: mantis.SubmitOrderResponse
	(*CancelOrderRequest)(nil),  // 2: mantis.CancelOrderRequest
	(*CancelOrderResponse)(nil), // 3: mantis.CancelOrderResponse
	(*GetDepthRequest)(nil),     // 4: mantis.GetDepthRequest
	(*GetDepthResponse)(nil),    // 5: mantis.GetDepthResponse
	(*StreamTradesRequest)(nil), // 6: mantis.StreamTradesRequest
	(*TradeEvent)(nil),          // 7: mantis.TradeEvent
	(Side)(0),                   // 8: mantis.Side
	(OrderType)(0),              // 9: mantis.OrderType
	(TimeInForce)(0),            // 10: mantis.TimeInForce
	(*Order)(nil),               // 11: mantis.Order
	(*Trade)(nil),               // 12: mantis.Trade
	(*OrderBookDepth)(nil),      // 13: mantis.OrderBookDepth
}
var file_mantis_matching_proto_depIdxs = []int32{
	8,  // 0: mantis.SubmitOrderRequest.side:type_name -> mantis.Side
	9,  // 1: mantis.SubmitOrderRequest.order_type:type_name -> mantis.OrderType
	10, // 2: mantis.SubmitOrderRequest.time_in_force:type_name -> mantis.TimeInForce
	11, // 3: mantis.SubmitOrderResponse.order:type_name -> mantis.Order
	12, // 4: mantis.SubmitOrderResponse.trades:type_name -> mantis.Trade
	11, // 5: mantis.CancelOrderResponse.order:type_name -> mantis.Order
	13, // 6: mantis.GetDepthResponse.depth:type_name -> mantis.OrderBookDepth
	12, // 7: mantis.TradeEvent.trade:type_name -> mantis.Trade
	0,  // 8: mantis.MatchingEngine.SubmitOrder:input_type -> mantis.SubmitOrderRequest
	2,  // 9: mantis.MatchingEngine.CancelOrder:input_type -> mantis.CancelOrderRequest
	4,  // 10: mantis.MatchingEngine.GetDepth:input_type -> mantis.GetDepthRequest
	6,  // 11: mantis.MatchingEngine.StreamTrades:input_type -> mantis.StreamTradesRequest
	1,  // 12: mantis.MatchingEngine.SubmitOrder:output_type -> mantis.SubmitOrderResponse
	3,  // 13: mantis.MatchingEngine.CancelOrder:output_type -> mantis.CancelOrderResponse
	5,  // 14: mantis.MatchingEngine.GetDepth:output_type -> mantis.GetDepthResponse
	7,  // 15: mantis.MatchingEngine.StreamTrades:output_type -> mantis.TradeEvent
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_mantis_matching_proto_init() }
func file_mantis_matching_proto_init() {
	if File_mantis_matching_proto != nil {
		return
	}
	file_mantis_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mantis_matching_proto_rawDesc), len(file_mantis_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mantis_matching_proto_goTypes,
		DependencyIndexes: file_mantis_matching_proto_depIdxs,
		MessageInfos:      file_mantis_matching_proto_msgTypes,
	}.Build()
	File_mantis_matching_proto = out.File
	file_mantis_matching_proto_goTypes = nil
	file_mantis_matching_proto_depIdxs = nil
}
