// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: mantis/order.proto

package mantis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          Side                   `protobuf:"varint,3,opt,name=side,proto3,enum=mantis.Side" json:"side,omitempty"`
	OrderType     OrderType              `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=mantis.OrderType" json:"order_type,omitempty"`
	TimeInForce   TimeInForce            `protobuf:"varint,5,opt,name=time_in_force,json=timeInForce,proto3,enum=mantis.TimeInForce" json:"time_in_force,omitempty"`
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`       // Decimal as string for precision.
	Quantity      string                 `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"` // Decimal as string for precision.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_mantis_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_mantis_order_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PlaceOrderRequest) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *PlaceOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type PlaceOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_mantis_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_mantis_order_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *PlaceOrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type CancelOrderByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderByUserRequest) Reset() {
	*x = CancelOrderByUserRequest{}
	mi := &file_mantis_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderByUserRequest) ProtoMessage() {}

func (x *CancelOrderByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderByUserRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderByUserRequest) Descriptor() ([]byte, []int) {
	return file_mantis_order_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CancelOrderByUserRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderByUserRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"` // The cancelled order, if found.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderByUserResponse) Reset() {
	*x = CancelOrderByUserResponse{}
	mi := &file_mantis_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderByUserResponse) ProtoMessage() {}

func (x *CancelOrderByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderByUserResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderByUserResponse) Descriptor() ([]byte, []int) {
	return file_mantis_order_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderByUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderByUserResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_mantis_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_mantis_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_mantis_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_mantis_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`                          // Optional filter by symbol.
	Status        OrderStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=mantis.OrderStatus" json:"status,omitempty"` // Optional filter by status.
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_mantis_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_mantis_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_mantis_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_mantis_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_mantis_order_proto protoreflect.FileDescriptor

const file_mantis_order_proto_rawDesc = "" +
	"\n" +
	"\x12mantis/order.proto\x12\x06mantis\x1a\x12mantis/types.proto\"\x83\x02\n" +
	"\x11PlaceOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12 \n" +
	"\x04side\x18\x03 \x01(\x0e2\f.mantis.SideR\x04side\x120\n" +
	"\n" +
	"order_type\x18\x04 \x01(\x0e2\x11.mantis.OrderTypeR\torderType\x127\n" +
	"\rtime_in_force\x18\x05 \x01(\x0e2\x13.mantis.TimeInForceR\vtimeInForce\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\"`\n" +
	"\x12PlaceOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.mantis.OrderR\x05order\x12%\n" +
	"\x06trades\x18\x02 \x03(\v2\r.mantis.TradeR\x06trades\"f\n" +
	"\x18CancelOrderByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"Z\n" +
	"\x19CancelOrderByUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\x05order\x18\x02 \x01(\v2\r.mantis.OrderR\x05order\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"7\n" +
	"\x10GetOrderResponse\x12#\n" +
	"\x05order\x18\x01 \x01(\v2\r.mantis.OrderR\x05order\"\x9f\x01\n" +
	"\x11ListOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12+\n" +
	"\x06status\x18\x03 \x01(\x0e2\x13.mantis.OrderStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"Q\n" +
	"\x12ListOrdersResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.mantis.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xab\x02\n" +
	"\fOrderService\x12C\n" +
	"\n" +
	"PlaceOrder\x12\x19.mantis.PlaceOrderRequest\x1a\x1a.mantis.PlaceOrderResponse\x12R\n" +
	"\vCancelOrder\x12 .mantis.CancelOrderByUserRequest\x1a!.mantis.CancelOrderByUserResponse\x12=\n" +
	"\bGetOrder\x12\x17.mantis.GetOrderRequest\x1a\x18.mantis.GetOrderResponse\x12C\n" +
	"\n" +
	"ListOrders\x12\x19.mantis.ListOrdersRequest\x1a\x1a.mantis.ListOrdersResponseB8Z6github.com/mantis-exchange/mantis-common/gen/go/mantisb\x06proto3"

var (
	file_mantis_order_proto_rawDescOnce sync.Once
	file_mantis_order_proto_rawDescData []byte
)

func file_mantis_order_proto_rawDescGZIP() []byte {
	file_mantis_order_proto_rawDescOnce.Do(func() {
		file_mantis_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mantis_order_proto_rawDesc), len(file_mantis_order_proto_rawDesc)))
	})
	return file_mantis_order_proto_rawDescData
}

var file_mantis_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mantis_order_proto_goTypes = []any{
	(*PlaceOrderRequest)(nil),         // 0: mantis.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),        // 1: mantis.PlaceOrderResponse
	(*CancelOrderByUserRequest)(nil),  // 2: mantis.CancelOrderByUserRequest
	(*CancelOrderByUserResponse)(nil), // 3: mantis.CancelOrderByUserResponse
	(*GetOrderRequest)(nil),           // 4: mantis.GetOrderRequest
	(*GetOrderResponse)(nil),          // 5: mantis.GetOrderResponse
	(*ListOrdersRequest)(nil),         // 6: mantis.ListOrdersRequest
	(*ListOrdersResponse)(nil),        // 7: mantis.ListOrdersResponse
	(Side)(0),                         // 8: mantis.Side
	(OrderType)(0),                    // 9: mantis.OrderType
	(TimeInForce)(0),                  // 10: mantis.TimeInForce
	(*Order)(nil),                     // 11: mantis.Order
	(*Trade)(nil),                     // 12: mantis.Trade
	(OrderStatus)(0),                  // 13: mantis.OrderStatus
}
var file_mantis_order_proto_depIdxs = []int32{
	8,  // 0: mantis.PlaceOrderRequest.side:type_name -> mantis.Side
	9,  // 1: mantis.PlaceOrderRequest.order_type:type_name -> mantis.OrderType
	10, // 2: mantis.PlaceOrderRequest.time_in_force:type_name -> mantis.TimeInForce
	11, // 3: mantis.PlaceOrderResponse.order:type_name -> mantis.Order
	12, // 4: mantis.PlaceOrderResponse.trades:type_name -> mantis.Trade
	11, // 5: mantis.CancelOrderByUserResponse.order:type_name -> mantis.Order
	11, // 6: mantis.GetOrderResponse.order:type_name -> mantis.Order
	13, // 7: mantis.ListOrdersRequest.status:type_name -> mantis.OrderStatus
	11, // 8: mantis.ListOrdersResponse.orders:type_name -> mantis.Order
	0,  // 9: mantis.OrderService.PlaceOrder:input_type -> mantis.PlaceOrderRequest
	2,  // 10: mantis.OrderService.CancelOrder:input_type -> mantis.CancelOrderByUserRequest
	4,  // 11: mantis.OrderService.GetOrder:input_type -> mantis.GetOrderRequest
	6,  // 12: mantis.OrderService.ListOrders:input_type -> mantis.ListOrdersRequest
	1,  // 13: mantis.OrderService.PlaceOrder:output_type -> mantis.PlaceOrderResponse
	3,  // 14: mantis.OrderService.CancelOrder:output_type -> mantis.CancelOrderByUserResponse
	5,  // 15: mantis.OrderService.GetOrder:output_type -> mantis.GetOrderResponse
	7,  // 16: mantis.OrderService.ListOrders:output_type -> mantis.ListOrdersResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_mantis_order_proto_init() }
func file_mantis_order_proto_init() {
	if File_mantis_order_proto != nil {
		return
	}
	file_mantis_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mantis_order_proto_rawDesc), len(file_mantis_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mantis_order_proto_goTypes,
		DependencyIndexes: file_mantis_order_proto_depIdxs,
		MessageInfos:      file_mantis_order_proto_msgTypes,
	}.Build()
	File_mantis_order_proto = out.File
	file_mantis_order_proto_goTypes = nil
	file_mantis_order_proto_depIdxs = nil
}
