// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: mantis/types.proto

package mantis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

// Enum value maps for Side.
var (
	Side_name = map[int32]string{
		0: "SIDE_UNSPECIFIED",
		1: "SIDE_BUY",
		2: "SIDE_SELL",
	}
	Side_value = map[string]int32{
		"SIDE_UNSPECIFIED": 0,
		"SIDE_BUY":         1,
		"SIDE_SELL":        2,
	}
)

func (x Side) Enum() *Side {
	p := new(Side)
	*p = x
	return p
}

func (x Side) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Side) Descriptor() protoreflect.EnumDescriptor {
	return file_mantis_types_proto_enumTypes[0].Descriptor()
}

func (Side) Type() protoreflect.EnumType {
	return &file_mantis_types_proto_enumTypes[0]
}

func (x Side) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Side.Descriptor instead.
func (Side) EnumDescriptor() ([]byte, []int) {
	return file_mantis_types_proto_rawDescGZIP(), []int{0}
}

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_LIMIT",
		2: "ORDER_TYPE_MARKET",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_LIMIT":       1,
		"ORDER_TYPE_MARKET":      2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_mantis_types_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_mantis_types_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_mantis_types_proto_rawDescGZIP(), []int{1}
}

type TimeInForce int32

const (
	TimeInForce_TIME_IN_FORCE_UNSPECIFIED TimeInForce = 0
	TimeInForce_TIME_IN_FORCE_GTC         TimeInForce = 1
	TimeInForce_TIME_IN_FORCE_IOC         TimeInForce = 2
	TimeInForce_TIME_IN_FORCE_FOK         TimeInForce = 3
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "TIME_IN_FORCE_UNSPECIFIED",
		1: "TIME_IN_FORCE_GTC",
		2: "TIME_IN_FORCE_IOC",
		3: "TIME_IN_FORCE_FOK",
	}
	TimeInForce_value = map[string]int32{
		"TIME_IN_FORCE_UNSPECIFIED": 0,
		"TIME_IN_FORCE_GTC":         1,
		"TIME_IN_FORCE_IOC":         2,
		"TIME_IN_FORCE_FOK":         3,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_mantis_types_proto_enumTypes[2].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_mantis_types_proto_enumTypes[2]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_mantis_types_proto_rawDescGZIP(), []int{2}
}

type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_NEW              OrderStatus = 1
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 2
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_NEW",
		2: "ORDER_STATUS_PARTIALLY_FILLED",
		3: "ORDER_STATUS_FILLED",
		4: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_NEW":              1,
		"ORDER_STATUS_PARTIALLY_FILLED": 2,
		"ORDER_STATUS_FILLED":           3,
		"ORDER_STATUS_CANCELLED":        4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mantis_types_proto_enumTypes[3].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_mantis_types_proto_enumTypes[3]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_mantis_types_proto_rawDescGZIP(), []int{3}
}

type Order struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol         string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side           Side                   `protobuf:"varint,3,opt,name=side,proto3,enum=mantis.Side" json:"side,omitempty"`
	OrderType      OrderType              `protobuf:"varint,4,opt,name=order_type,json=orderType,proto3,enum=mantis.OrderType" json:"order_type,omitempty"`
	TimeInForce    TimeInForce            `protobuf:"varint,5,opt,name=time_in_force,json=timeInForce,proto3,enum=mantis.TimeInForce" json:"time_in_force,omitempty"`
	Price          string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"` // Decimal as string for precision
	Quantity       string                 `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	FilledQuantity string                 `protobuf:"bytes,8,opt,name=filled_quantity,json=filledQuantity,proto3" json:"filled_quantity,omitempty"`
	Status         OrderStatus            `protobuf:"varint,9,opt,name=status,proto3,enum=mantis.OrderStatus" json:"status,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp millis
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_mantis_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_mantis_types_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() Side {
	if x != nil {
		return x.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Order) GetOrderType() OrderType {
	if x != nil {
		return x.OrderType
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Order) GetFilledQuantity() string {
	if x != nil {
		return x.FilledQuantity
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	MakerOrderId  string                 `protobuf:"bytes,5,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId  string                 `protobuf:"bytes,6,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	MakerSide     Side                   `protobuf:"varint,7,opt,name=maker_side,json=makerSide,proto3,enum=mantis.Side" json:"maker_side,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_mantis_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_mantis_types_proto_rawDescGZIP(), []int{1}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Trade) GetMakerOrderId() string {
	if x != nil {
		return x.MakerOrderId
	}
	return ""
}

func (x *Trade) GetTakerOrderId() string {
	if x != nil {
		return x.TakerOrderId
	}
	return ""
}

func (x *Trade) GetMakerSide() Side {
	if x != nil {
		return x.MakerSide
	}
	return Side_SIDE_UNSPECIFIED
}

func (x *Trade) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type DepthLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepthLevel) Reset() {
	*x = DepthLevel{}
	mi := &file_mantis_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthLevel) ProtoMessage() {}

func (x *DepthLevel) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthLevel.ProtoReflect.Descriptor instead.
func (*DepthLevel) Descriptor() ([]byte, []int) {
	return file_mantis_types_proto_rawDescGZIP(), []int{2}
}

func (x *DepthLevel) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *DepthLevel) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type OrderBookDepth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bids          []*DepthLevel          `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*DepthLevel          `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookDepth) Reset() {
	*x = OrderBookDepth{}
	mi := &file_mantis_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookDepth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookDepth) ProtoMessage() {}

func (x *OrderBookDepth) ProtoReflect() protoreflect.Message {
	mi := &file_mantis_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookDepth.ProtoReflect.Descriptor instead.
func (*OrderBookDepth) Descriptor() ([]byte, []int) {
	return file_mantis_types_proto_rawDescGZIP(), []int{3}
}

func (x *OrderBookDepth) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderBookDepth) GetBids() []*DepthLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBookDepth) GetAsks() []*DepthLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

var File_mantis_types_proto protoreflect.FileDescriptor

const file_mantis_types_proto_rawDesc = "" +
	"\n" +
	"\x12mantis/types.proto\x12\x06mantis\"\xe3\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12 \n" +
	"\x04side\x18\x03 \x01(\x0e2\f.mantis.SideR\x04side\x120\n" +
	"\n" +
	"order_type\x18\x04 \x01(\x0e2\x11.mantis.OrderTypeR\torderType\x127\n" +
	"\rtime_in_force\x18\x05 \x01(\x0e2\x13.mantis.TimeInForceR\vtimeInForce\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x12'\n" +
	"\x0ffilled_quantity\x18\b \x01(\tR\x0efilledQuantity\x12+\n" +
	"\x06status\x18\t \x01(\x0e2\x13.mantis.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\"\xf9\x01\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12$\n" +
	"\x0emaker_order_id\x18\x05 \x01(\tR\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x06 \x01(\tR\ftakerOrderId\x12+\n" +
	"\n" +
	"maker_side\x18\a \x01(\x0e2\f.mantis.SideR\tmakerSide\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\">\n" +
	"\n" +
	"DepthLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\"x\n" +
	"\x0eOrderBookDepth\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12&\n" +
	"\x04bids\x18\x02 \x03(\v2\x12.mantis.DepthLevelR\x04bids\x12&\n" +
	"\x04asks\x18\x03 \x03(\v2\x12.mantis.DepthLevelR\x04asks*9\n" +
	"\x04Side\x12\x14\n" +
	"\x10SIDE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSIDE_BUY\x10\x01\x12\r\n" +
	"\tSIDE_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x01\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x02*q\n" +
	"\vTimeInForce\x12\x1d\n" +
	"\x19TIME_IN_FORCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_IN_FORCE_GTC\x10\x01\x12\x15\n" +
	"\x11TIME_IN_FORCE_IOC\x10\x02\x12\x15\n" +
	"\x11TIME_IN_FORCE_FOK\x10\x03*\x99\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ORDER_STATUS_NEW\x10\x01\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x02\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x03\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x04B8Z6github.com/mantis-exchange/mantis-common/gen/go/mantisb\x06proto3"

var (
	file_mantis_types_proto_rawDescOnce sync.Once
	file_mantis_types_proto_rawDescData []byte
)

func file_mantis_types_proto_rawDescGZIP() []byte {
	file_mantis_types_proto_rawDescOnce.Do(func() {
		file_mantis_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mantis_types_proto_rawDesc), len(file_mantis_types_proto_rawDesc)))
	})
	return file_mantis_types_proto_rawDescData
}

var file_mantis_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_mantis_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mantis_types_proto_goTypes = []any{
	(Side)(0),              // 0: mantis.Side
	(OrderType)(0),         // 1: mantis.OrderType
	(TimeInForce)(0),       // 2: mantis.TimeInForce
	(OrderStatus)(0),       // 3: mantis.OrderStatus
	(*Order)(nil),          // 4: mantis.Order
	(*Trade)(nil),          // 5: mantis.Trade
	(*DepthLevel)(nil),     // 6: mantis.DepthLevel
	(*OrderBookDepth)(nil), // 7: mantis.OrderBookDepth
}
var file_mantis_types_proto_depIdxs = []int32{
	0, // 0: mantis.Order.side:type_name -> mantis.Side
	1, // 1: mantis.Order.order_type:type_name -> mantis.OrderType
	2, // 2: mantis.Order.time_in_force:type_name -> mantis.TimeInForce
	3, // 3: mantis.Order.status:type_name -> mantis.OrderStatus
	0, // 4: mantis.Trade.maker_side:type_name -> mantis.Side
	6, // 5: mantis.OrderBookDepth.bids:type_name -> mantis.DepthLevel
	6, // 6: mantis.OrderBookDepth.asks:type_name -> mantis.DepthLevel
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_mantis_types_proto_init() }
func file_mantis_types_proto_init() {
	if File_mantis_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mantis_types_proto_rawDesc), len(file_mantis_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mantis_types_proto_goTypes,
		DependencyIndexes: file_mantis_types_proto_depIdxs,
		EnumInfos:         file_mantis_types_proto_enumTypes,
		MessageInfos:      file_mantis_types_proto_msgTypes,
	}.Build()
	File_mantis_types_proto = out.File
	file_mantis_types_proto_goTypes = nil
	file_mantis_types_proto_depIdxs = nil
}
